### PR TITLE
Forefront TMG auth implementation

### PR DESCRIPTION
**Pull request by koltyakov**
Hey Sergei,

Could you please take a look at authentication implementation for SharePoint environment located behind Forefront TMG reverse proxy?

Dealing with TMG, a POST request to `/CookieAuth.dll?Logon` is sent with `application/x-www-form-urlencoded` body, containing login (in `domain\username` format) and password.

At the moment, it ignores `domain` option, the auth object should look like:

```json
{
    "username": "domain\\username",
    "password": "Pas$word",
    "tmg": true
}
```

Brief tests allowed me to communicate with new auth strategy:

image

Unfortunately, I can't provide you environment for testing. But will ask for a possibility.
It would be great if you could merge this auth strategy at least in experimental mode, as far as it doesn't conflict with other strategies it's save to go.

Thanks!

### CODE REVIEW

**Comment by koltyakov** [comment]
Just for the record: new auth method also was added to `node-sp-auth-config` (dev commits), so I can merge and publish the update for config project ASAP.

**Comment by s-KaiNet** [comment]
```javascript
export const TmgAuthEndpoint = 'CookieAuth.dll?Logon'
```
I have never thought that I will merge such kind of things in this repository 
But you never know :)    

Thanks Andrew, I will take a look today's evening.

**Comment by s-KaiNet** [comment]
Merged manually. I haven't had a chance to test it, because I don't have configured TMG, but I completely trust you :)

**Comment by koltyakov** [comment]
Thanks, man!

**Pull request closed without merging**
